name: conodia
description: Build a powerfull Discord applications in Dart
version: 1.0.0

publish_to: none

environment:
 sdk: '>=2.17.0 <3.0.0'

dependencies:
 intl: ^0.18.0
 mineral:
  path: ../mineral-core
 mineral_invite:
  path: ../InviteMineral
 path: ^1.8.3
 yaml: ^3.1.1
 html: ^0.15.1
 udp: ^5.0.3
 json_annotation: ^4.8.0
 mineral_contract: ^1.1.0
dev_dependencies:
 build_runner: ^2.3.3
 freezed: ^2.3.2
 json_serializable: ^6.6.1
 lints: ^1.0.0
 test: ^1.16.0
